server:
  port: 8080

spring:
  application:
    name: rentex

  config:
    import: optional:classpath:application-secret.properties,optional:file:./application-secret.properties

  datasource:
    url: jdbc:mariadb://localhost:3307/rentex
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:init/rentex.sql

  web:
    resources:
      static-locations:
        - classpath:/static/           # 정적 리소스 (빌드 시 포함된 기본 이미지)
        - file:${file.upload-dir}/     # 업로드 파일 (외부 경로)

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

# ===================================
# ✅ 업로드 파일 저장 경로
# ===================================
file:
  upload-dir: ./uploads
  # 🟢 AWS 배포 시: /home/ubuntu/rentex/uploads 로 변경

# ===================================
# ✅ 프론트엔드 도메인 주소 (CORS 허용)
# ===================================
app:
  frontend-url: http://localhost:3000
  # 🟢 AWS 배포 시: https://rentex.site 같은 실제 프론트 주소로 변경

## 테스트
#  debug: true
#  logging:
#    level:
#      org.springframework.boot.context.config: TRACE
#      org.springframework.core.env: TRACE
#
